version: '3'
services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - MONGO_URI=${MONGO_URI}
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
